# Makefile for AW_View
# 
# @author Eduardo Calderini Jr <ecalderini@ydeasolutions.com.br>




################
# Main targets #
################
all: libs

libs:
	gnatmake -P kowview-entities.gpr

clean: 
	gnatclean -P kowview-entities.gpr
	@echo "All clean"

docs:
	@-./gendoc.sh
	@echo "The documentation is generated by a bash script. Then it might fail in other platforms than Linux"

install:
	@cat INSTALL
# TODO: implement the install target	
# FIXME: I should create gpr files to be included by other projects.

